server:
  port: 8080

spring:
  spring:
    application:
      name: ecms-server

  profiles:
    default: local # 기본 환경을 dev로

management:
  endpoints:
    web:
      exposure:
        include: "prometheus"