server:
  port: 7777

spring:
  config:
    activate:
      on-profile: local # 환경이름설정

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:13306/ecms_db_dev?characterEncoding=UTF-8&serverTimezone=UTC
    username: cookyuu
    password: hk1234
    hikari:
      maximum-pool-size: 60

  jpa:
    hibernate:
      :ddl-auto: update
    properties:
      hibernate:
#        format_sql: true
#        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    auditing:
      enabled: true

  data:
    redis:
#      host: redis
      host: 127.0.0.1
      port: 6379

auth:
  jwt:
    secret: TESTECMSSECRETKEYISJWTTESTTESTECMSSECRETKEYISJWTTEST
    access:
      exp: 30 # 30분 : 1000*60*30
    refresh:
      exp: 10080 # 7일 : 1000*60*60*24*7 24 * 60 * 7 420 * 24 = 1680 + 8400 = 10080

logging:
  level:
    com.cookyuu.ecms_server: debug
    org.hibernate.SQL: debug
    org.hibernate.type: trace

slack:
  webhook:
    url: ${SLACK_WEBHOOK_URL}
