spring:
  application:
    name: ecms-server


  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:23306/ecms_db?characterEncoding=UTF-8&serverTimezone=UTC
    username: hklim
    password: hk1234
    hikari:
      maximum-pool-size: 60

    jpa:
      hibernate:
        :ddl-auto: none
      properties:
        hibernate:
          format_sql: true
          show_sql: false
      auditing:
        enabled: true